name: Build and Publish image to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build images
        run: |
          docker build ./api -t tansib007/docker-fastapi:latest
          docker build ./front-end-nextjs -t tansib007/devops-qr-code-front-end:latest
      - name: Login to DockerHub
        run:  echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u tansib007 --password-stdin
      - name: push back-end API image to Docker Hub
        run: docker push tansib007/docker-fastapi:latest
      - name: push front-end image to Docker Hub
        run: docker push tansib007/devops-qr-code-front-end:latest